create userdata for the instance and open port 80 for http requests
mohanedmoh/DevOps-Mentorship-program pull request #9
Opened 2023-02-13 21:55 UTC by mohanedmoh

2023-02-13 22:49 UTC, geoffrey1330 requested changes

2023-02-13 22:49 UTC, geoffrey1330 commented on Terraform/AWS/task6/terraform.tfvars
> +my_ip        = ["90.240.135.206/32"]
add newline at end of file.

2023-02-13 22:49 UTC, geoffrey1330 commented on Terraform/AWS/task6/userdata.sh
> +service apache2 restart
add newline at end of file.

2023-02-13 22:49 UTC, geoffrey1330 commented on Terraform/AWS/task6/variables.tf
> +variable "my_ip" {}
add newline at end of file.

2023-02-13 23:55 UTC, mohanedmoh commented on Terraform/AWS/task6/variables.tf
> +variable "my_ip" {}
updated

2023-02-15 10:20 UTC, geoffrey1330 approved these changes

2023-02-15 10:21 UTC, merged